### ISSUE TITLE
#1 Colores

### ISSUE THREAD

**Issue by PabloMontesMorquecho** [RubsRubs/HuertAPP2#1]
Dedicar un tiempo, usando distintas herramientas, sobre la teoría del color, para definir los colores corporativos.

Una vez establecida la paleta, los podemos implementar vía HuertAPP2/app/src/main/res/values/colors.xml, aunque tal vez deberíamos investigar sobre el uso de Material Design, e incorporar un estilo predefinido que se acerque a nuestras necesidades.

**Comment by PabloMontesMorquecho** [comment]
[https://youtu.be/ynOUzHFFMeg](https://youtu.be/ynOUzHFFMeg)
Añado enlace a vídeo tutorial que explica a la perfección todas las posibilidades que tenemos en Android para customizar la interfaz gráfica.

**Comment by PabloMontesMorquecho** [comment]
[https://www.materialpalette.com/](https://www.materialpalette.com/)
En esta página podemos probar el aspecto que tendrá nuestra aplicación y generar una combinación de colores apropiada antes de incorporarla al proyecto.

![Combinación Colores APP · Teal   Lime](https://user-images.githubusercontent.com/51938150/152115658-fa5e87d6-0a98-4b21-b66c-46cd13c7fbf3.jpg)

**Comment by RubsRubs** [comment]
Ok, estoy de acuerdo con tus colores, hay que mirar también el DarkMode
